version: '3'

# Setup node container
services:
  client:
    container_name: client
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    links:
      - server
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
